export const flatten = (value: string) => {
  value = value.trim();
  value = removeAccents(value);
  value = value.toLowerCase();
  return value;
};

export const removeAccents = (value: string) => {
  return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
};

export const isGoodTag = (value) => {
  let goodPossibleTags = [
    ...new Set([
      'magnifica',
      'purga',
      'primera',
      'acero',
      'aluminio',
      'inoxidable',
      'anodizado',
      'plato',
      'conector',
      'base',
      'goma',
      'imantado',
      'fijacion',
      'perfecta',
      'pequena',
      'gran purga',
      'nueva',
      'exclusiva',
      'resina',
      'epoxy',
      'innovador',
      'mastil',
      'jetpack',
      'alta',
      'polimero',
      'orificios',
      'manguera',
      'practica',
      'cristal',
      'maletin',
      'muelle',
      'elegancia',
      'autentica',
      'madera',
      'acrilica',
      'innovadora',
      'preciosa',
      'combinada',
      'boquilla',
      'lujo',
      'rusia',
      'diferencia',
      'nuevo',
      'diferente',
      'economica',
      'tallada',
      'moderna',
      'barata',
      'estilizado',
      'alemana',
      'metal',
      'brutal',
      'led',
      'joya',
      'accesorios',
      'seguridad',
      'novedosa',
      'artesanal',
      'estetica',
      'unica',
      'magnetico',
      'brasileno',
      'original',
      'espejo',
      'prisma',
      'cobre',
      'steel',
      'suave',
      'blue',
      'celeste',
      'deluxe',
      'gold',
      'bohemia',
      'espana',
      'diamond',
      'germany',
      'titanio',
      'cafe',
      'carbonica',
      'tradicional',
      'egipto',
      'exotica',
      'calavera',
      'americana',
      'spiderman',
      'camuflaje',
      'turquia',
      'turkey',
      'amarillo',
      'plateado',
      'turquesa',
      'marron',
      'oferta',
      'low cost',
      'plateada',
      'naranja',
      'ceramica',
      'navidad',
    ]),
  ];
  return goodPossibleTags.includes(flatten(value));
};
